services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "54:53/tcp"    # DNS
      - "55:53/udp"    # DNS
      - "84:80/tcp"    # Web admin
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=<your_timezone>
      - WEBPASSWORD=<your_admin_password>
    cap_add:
      - NET_ADMIN
