version: '2'
services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    # - "8888:8888" # proxy support
  volumes:
    - /path/to/data/:/data # where transmission will store the data
    - ./:/config # where transmission-home is stored
  environment:
    - OPENVPN_PROVIDER=<your_provider>
    - OPENVPN_CONFIG=<your_config>
    - OPENVPN_USERNAME=<your_username>
    - OPENVPN_PASSWORD=<your_password>
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 
    - LOCAL_NETWORK=192.168.2.0/24
    - TRANSMISSION_WEB_UI=flood-for-transmission   

 # proxy:
 #  image: haugene/transmission-openvpn-proxy
 #  links:
 #    - transmission
 #  ports:
 #    - 8080:8080
 #  volumes:
 #    - /etc/localtime:/etc/localtime:ro

 # rss:
 #  image: haugene/transmission-rss
 #  links:
 #    - transmission
 #  environment:
 #    - RSS_URL=http://.../xxxxx.rss
