services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - "8091:8080"
    volumes:
      - ./training-data:/usr/share/tessdata
      - ./extra-configs:/configs
      - ./logs:/logs
    environment:
      - DOCKER_ENABLE_SECURITY=false
