---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- logo:
    icon: homepage
    
- resources:
    cpu: true
    memory: true
    label: My Server

- resources:    
    disk: /
    label: Storage

- search:
    provider: duckduckgo
    target: _blank


